### ISSUE TITLE
.tape added to gitignore without newline

### ISSUE THREAD

**Issue by joshvc** [smashingboxes/taperole#55]
You wind up with a gitignore with a last line that looks like `database.yml.tape`, which is bad, because now neither `database.yml` _nor_ `.tape` are getting ignored.

**Comment by BrandonMathis** [comment]
I'm not currently seeing this behavior on master :(

What version of taperole are you using? I may have some changes on master that need to be released.

**Comment by joshvc** [comment]
Well, I first ran on 1.0.0 and have since updated to 1.1.3, but I suspect the behavior came from 1.0.0.

**Comment by BrandonMathis** [comment]
Okay, not seeing this happen in the latest version. Pretty sure I saw and fixed this a few weeks back. I'm gonna close this issue for now. Thx for the report.

**Comment by joshvc** [comment]
Yeah, forgot to report back, a new app using a more recent version worked with no issues. It's been resolved for sure.
