### ISSUE TITLE
Tape upgrade process is rickity

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/taperole#58]
The taperole gem update process needs to be brushed up. Currently, updating tape does not change the roles path in `.tape/ansible.cfg`.
- [ ] Write tape update docs
- [ ] Include some `.tape/ansible.cfg` update process when running tape installer install after update

**Comment by dkniffin** [comment]
@BrandonMathis Not sure if this ever got addressed, but it'd be nice if tape had a `tape update` command or something. I just tried upgrading GR to tape 1.3 and it's not immediately apparent what needs to change in the app. I eventually figured out that the configs moved to a directory, but it'd be nice if there was a command that did the update for me, or at least told me what needs to change.

**Comment by BrandonMathis** [comment]
This is an interesting problem because the intention right now is that servers provisioned with 1.2 are not compatible with 1.3.

We follow SemVer but not 100% correctly. The move from 1.2 to 1.3 was more like a 1.0 to 2.0 jump but I don't like the connotations that a "2.0" release has. It feels like saying "This is super stable and widely used" which tape is not yet.

We likely need to update the readme with some update procedures that will read something like this.

1. gem upgrade tape
1. start up a new server
1. delete all tape files from repo
1. `tape installer install`
1. `tape ansible everything`
1. pg_dump your db
1. scp your dumped db to your new server
1. rsync any other data (files, images, ect) onto your new server

**Comment by BrandonMathis** [comment]
While we could write a tape upgrade task. I think it is better to think of your application servers as things you can just knock down and stand back up on demand.

If you are moving from a major version release of tape to another, you should stand up a new server and migrate you DB. I would rather tape not hide this by creating some step-by-step wizard walking people through the process of that.

I am calling this "out of scope" and closing for now.
