### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/taperole#71]
Ideally, we should be able to give the SSL cert paths, and tape handle the rest

**Comment by BrandonMathis** [comment]
Hmmm, currently we do this by having people cp their ssl certs into a directory so that they are apart of the repo and always accessible by tape.

**Comment by dkniffin** [comment]
fyi, this came out of a slack convo on 12/14

**Comment by BrandonMathis** [comment]
Pretty sure we can close this. I am satisfied w/the way that tape handles ssl certs and we cannot give paths to tape unless they are relative to the repo that tape is installed in.
