### ISSUE TITLE
Remove need for "Waiting for secrets.yml"

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/taperole#75]
This step seems kind of clunky. Instead of waiting for the user to create the file, couldn't we just create it with a random sequence for the secret_key?

**Comment by BrandonMathis** [comment]
While this role is clunky, you still do need to take time to ssh into an application and hand-configure somethings like API keys, ect. Until we start using something like ansible-vault to encrypt and store all our keys in version control I say we stick with the "waiting for secrets.yml" thing.

Closing for now.
