### ISSUE TITLE
Added support for Node express APIs

### ISSUE THREAD

**Issue by BrandonMathis** [smashingboxes/taperole#80]
At Smashing Boxes, we want to be able to deploy node apps with tape. So I want to take a minute to discuss what that looks like and what the best approaches are for detecting a node backend app, deploying it, starting/restarting it, ect.
## Detecting a Node app

[Currently we look if there is a `configs.ru` or `package.json` in your projects root to tell if it is a rails of Frontend app](https://github.com/smashingboxes/taperole/blob/master/lib/tape.rb#L47-L53). Depending on what tape detect, the playbook that it decides to use for provisioning and deployment are very different. So, I need some way that we can differentiate betweeen a node backend app an Angular/React frontend app.
## Default Node Version

I usually default to the LTS version of anything I install on a server. Is it okay if we just always use 4.2 until the latest version come out or do we want to default to the latest version of node that we can install (as we do with ruby).
## Monit config

Is this as simple as `node index.js`? Or is there some kind of better node runner that we should use?
## Mongodb

If we are going node then it is only proper that we also get some mongodb.
## Docker

Would be **very** interested in doing some pairing on a possible Docker focused ansible-driven provisioning and deployment setup. I've been wanting to move our system over to docker for a while now. But.... I will need help. 
### Issues to resolve in this thread
- [ ] How will tape detect that it is looking at a node backend app?
- [ ] Should we only use node 4.2 LTS or is it okay to use the latest version of node?
- [ ] Monit start/stop script
- [ ] Mongodb
- [ ] Docker

**Comment by keeganbrown** [comment]
To start the convo:

# RE: Detecting a Node app
I'd suggest we use [PM2](https://github.com/Unitech/pm2) as a process manager. PM2 gives us the option to build an `ecosystem.json` file that we can use for detection of an BE node app. It's also got a lot of other bells and whistles that can come in handy. _PM2 even does deployment, not like we need that with tape..._

# RE: Node Version
100% with you on LTS.

# RE: Monit
AFAIK PM2 replaces all the functionality of Monit.

# RE: Mongo
I'm a big fan of MongoDB too, so +1 on this. I've got boilerplate shell scripts for a vagrant setup I use if you want to use them for reference.

# RE: Docker
IMHO, this is a more important feature, and could make a lot of the rest of this issue moot -- I'd say start with Docker, and then build Node apps on top of docker. I'm down to help and I think @joeyjoejoejr is too.

**Comment by joeyjoejoejr** [comment]
I'm on it!

**Comment by BrandonMathis** [comment]
@joeyjoejoejr here is what I am thinking (lets try to keep this contained to node apps only and we can expand out to rails/fe_static).

1. Create a `templates/node`
1. Put some Docker files that define containers in `templates/node/docker`
1. Create a node ombibox.yml playbook inside `templates/node`
1. Copy those :top: files into the apps local dir when you run `tape installer install` (they should go into the `taperole` dir that get created as apart of that process
1. Create some roles that utilize the [Ansible Docker Module](http://docs.ansible.com/ansible/docker_module.html) for standing up our docker container(s)
1. Create some Dockerfile(s) in a `docker` dir that tape can use when it runs `tape ansible everything` (should Just Work :tm: )

Challenge may getting the path to the Dockerfile(s) right. I think that they can just be kept inside the tape source and our of the App's source. If not, you could maybe do some trickery kinda like what I have done in the past [here](https://github.com/smashingboxes/taperole/blob/master/lib/tape/ansible_runner.rb#L100-L112)?
